### PR TITLE
Fix bug in k=0.

### LINKED ISSUE #48: The degree = 0L case is wrong
```r
y <- c(1, rpois(100, dnorm(1:100, 50, 15) * 500 + 1))
out <- estimate_rt(y, nsol = 10)
plot(out)
out0 <- estimate_rt(y, degree = 0L, nsol = 10)
plot(out0)
```

Seems to be operating on cases rather than Rt.

### PR DESCRIPTION
**Pull request by jiapivialiu**
Fix #48.

### CODE REVIEW

**Comment by dajmcdon** [comment]
These are both pretty small modifications. And they would seem to also affect the `degree > 0` cases. Can you give me a bit of context as to why this is the fix?

**Comment by jiapivialiu** [comment]
Both fixes target only the k=0 case and are made only in the functions of dynamic programming (DP) algorithm.

For the $\lambda$ fix, the DP algorithm solves the objective without the loss part divided by the sequence length $n$, but the proximal Newton for degree>0 solves the loss divided by $n$, so $\lambda$ passed into the DP algorithm should be multiplied by $n$, but I forgot it earlier.

The other fix is a typo in the DP algorithm, I made small modifications to the original DP algorithm to take past infections as weights. I divided the original signals by the weights ($yw=y/w$) at the beginning of the algorithm and used $yw$ throughout the algorithm. Using $y$ for these specific lines was a typo.

**Comment by dajmcdon** [comment]
I see. The difference being that for `degree > 0` we use `dptf()` in the ADMM but for `degree = 0` we use `dptf_past()`. 

* Can you rename `dptf_past()` to `wdptf()` or something? The difference is the weighting. I'm not sure what `_past` indicates.

**Comment by dajmcdon** [comment]
And merge `main` so I can approve the PR.

**Review by dajmcdon — CHANGES_REQUESTED** [review]
See comments above.

**Comment by jiapivialiu** [comment]
Solve #51.

**Review by dajmcdon — APPROVED** [review]

**Pull request merged**
